package com.pascualteam.javaproject.controller;

import com.pascualteam.javaproject.model.repository.User;
import com.pascualteam.javaproject.model.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@RestController 	// This means that this class is a Controller
@RequestMapping(path="/userAPI") // This means URL's start with /demo (after Application path)
@CrossOrigin("*")
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path="/save")
	public User save(@RequestBody User user) {
		User obj = userRepository.save(user);
		return obj;
	}

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String firstname
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setFirstname(firstname);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/user/{id}")
	public User getById(@PathVariable Integer id) {
		return userRepository.findById(id).get();
	}
}
